version: "3.9"

services:

  database: 
    image: postgres:14.2-bullseye
    volumes:
      - personalProject:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=planets
      - POSTGRES_PASSWORD=test-databases
    ports:
      - 15432:5432

  planet-api:
    build:
      context: ./planet_app/api
      dockerfile: ./Dockerfile
    ports:
      - "8100:8000"
    volumes:
      - ./planet_app/api:/app
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://planets:password@database:5432/planets
      WAIT_HOSTS: database:5432
      WAIT_TIMEOUT: 240
      
volumes:
  personalProject:
    external: true
