# Generated by Django 4.2.2 on 2023-06-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planet", "0003_remove_planetsystem_planets_planet_planets"),
    ]

    operations = [
        migrations.AddField(
            model_name="planetsystem",
            name="image",
            field=models.URLField(default=True),
        ),
    ]
