# Generated by Django 4.2.2 on 2023-06-14 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("planet", "0005_rename_planets_planet_systems"),
    ]

    operations = [
        migrations.AddField(
            model_name="planetsystem",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="planet",
            name="systems",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planets",
                to="planet.planetsystem",
            ),
        ),
    ]
