# Generated by Django 4.2.2 on 2023-08-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planet", "0006_planetsystem_description_alter_planet_systems"),
    ]

    operations = [
        migrations.AddField(
            model_name="planet",
            name="distance",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="planet",
            name="mass",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="planet",
            name="temperature",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="planet",
            name="image",
            field=models.URLField(default=True),
        ),
        migrations.AlterField(
            model_name="planet",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
