# Generated by Django 4.2.2 on 2023-08-03 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planet", "0007_planet_distance_planet_mass_planet_temperature_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planet",
            old_name="systems",
            new_name="system",
        ),
    ]
