# Generated by Django 4.2.2 on 2023-06-12 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("planet", "0002_planetsystem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planetsystem",
            name="planets",
        ),
        migrations.AddField(
            model_name="planet",
            name="planets",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planets",
                to="planet.planetsystem",
            ),
        ),
    ]
