# Generated by Django 4.2.2 on 2023-06-13 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planet", "0004_planetsystem_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planet",
            old_name="planets",
            new_name="systems",
        ),
    ]
